apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata: 
    name: kccm-sa
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kccm
  subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: default
kind: List
metadata: {}